[package]
name = "libchm"
version = "0.2.0"
description = "Pure-Rust CHM file reader."
edition = "2024"
license = "MIT"
repository = "https://github.com/trypsynth/libchm"
keywords = ["chm", "parser", "lzx", "ebook"]
categories = ["parser-implementations"]

[dependencies]
thiserror = "2.0.18"
bitflags  = "2"
